FROM gradle AS build

WORKDIR /app

COPY . .

RUN gradle assemble

FROM amazoncorretto:11

COPY --from=build /app/build/libs/*.jar ./

EXPOSE 8080
EXPOSE 18080

ENTRYPOINT ["java", "-Xrunjdwp:server=y,transport=dt_socket,address=18080,suspend=n", "-jar", "./koodihaaste22-0.0.1-SNAPSHOT.jar"]